version: '3.8'

services:
  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
    container_name: db_container
    image: ${DOCKER_DB_IMAGE_NAME}:latest
    ports:
      - 3306:3306  # 호스트와 컨테이너 간의 포트 매핑
    environment:
      environment:
      SPRING_PROFILES_ACTIVE: dev
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${MYSQL_TZ}
    volumes:
      - mysql_data:/var/lib/mysql # 데이터 영구 저장을 위한 볼륨 마운트
      - ${MYSQL_CUSTOM_CONFIG_PATH}:/etc/mysql/conf.d
      - ${MYSQL_DEFAULT_CONFIG_FILE}:/etc/my.cnf
      - ${MYSQL_INIT_SCRIPTS_PATH}:/docker-entrypoint-initdb.d  # 초기화 스크립트 마운트
    networks:
      - ticket_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${PROJECT_NAME}:latest
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    restart: always
    networks:
      - ticket_network

networks:
  ticket_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local