version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing:latest
    container_name: app-container
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    networks:
      - ticket_network

networks:
  ticket_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local