version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ticketing-local:latest
    container_name: app-container
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
    restart: always
    networks:
      - ticket_network

networks:
  ticket_network:
    external: true