version: '3.8'

services:
  app:
    image: ${ECR_URI}/${PROJECT_NAME}
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    networks:
      - ticket_network

networks:
  ticket_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local