version: '3.8'

services:
  app:
    image: ${ECR_URI}/${ECR_NAME}
    container_name: app_container
    ports:
      - 8080:8080
      - 80:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
