version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILES_ACTIVE=prod
    image: ${ECR_URI}/${ECR_NAME}
    container_name: app_container
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env.prod
    restart: always
