debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fc.springprojectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  application:
    name: ticketing

  datasource:
    url: jdbc:mysql://localhost:13306/
    username: developer
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

  sql:
    init:
      mode: always

  data.rest:
    base-path: /api
    detection-strategy: annotated
