logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    redisratelimiter: DEBUG

server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
    gateway:
      httpclient:
        connect-timeout: 3600000 # 1hour
        response-timeout: 3600000 # 1hour
      discovery:
        locator:
          enabled: true

  jackson:
    time-zone: Asia/Seoul
    property-naming-strategy: SNAKE_CASE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  app:
    jwtSecretKey: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==
  access-token-validity: 86400000 # 1 day
  refresh-token-validity: 1296000000 # 15 days