debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com.mgnt.ticketing: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8081
  error:
    whitelabel:
      enabled: true
    include-message: always
  servlet:
    context-path: /
    context-parameters:
      throwExceptionIfNoHandlerFound: true

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
    username: developer # 데이터베이스 사용자 이름을 'developer'로 설정합니다.
    password: 12345 # 데이터베이스 사용자 비밀번호를 '12345'로 설정합니다.
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스를 사용합니다.




jwt:
  secret: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="
  access-token-validity: 3600000 # 1 hour
  refresh-token-validity: 1296000000 # 15 days

eureka:
  client:
    register-with-eureka: true #유레카 서버에 등록할지 여부
    fetch-registry: true #유레카 서버의 정보를 가져올지 여부
    service-url.defaultZone: http://admin:1234@localhost:8761/eureka #유레카 서버 주소
  instance:
    prefer-ip-address: true
gateway:
  ip: 172.30.1.0/24