spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hyeseong43@gmail.com
    password: xkgy ntsq fkrr zbmz

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=="
  access-token-validity: 3600000 # 1 hour
  refresh-token-validity: 1296000000 # 15 days
