debug: false

logging:
  level:
    org.springframework.security: DEBUG
    com.mgnt.userservice: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8082
  error:
    whitelabel:
      enabled: true
    include-message: always
  servlet:
    context-path: /
    context-parameters:
      throwExceptionIfNoHandlerFound: true

spring:
  application:
    name: concert-service
  config:
    import:
      - classpath:/application-prod.yml
      - classpath:/application-local.yml
      - classpath:/application-secrets.yml

  datasource:
    hikari:
      maximum-pool-size: 10
      max-lifetime: 150000
      idle-timeout: 600000
      connection-timeout: 30000
      validation-timeout: 5000
    url: jdbc:mysql://localhost:3309/ticketing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true
    username: developer
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
    property-naming-strategy: SNAKE_CASE
  web:
    resources:
      add-mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 50
  kafka:
    bootstrap-servers: localhost:9092,kafka:9092
    consumer:
      group-id: concert-service-group