debug: false

logging:
  level:
    org.springframework.security: DEBUG
    com.mgnt.concertservice: INFO
    org.hibernate: INFO
    com.zaxxer.hikari: INFO

server:
  port: 8082
  error:
    whitelabel:
      enabled: true
    include-message: always
  servlet:
    context-path: /
    context-parameters:
      throwExceptionIfNoHandlerFound: true
  tomcat:
    max-threads: 800
    max-connections: 20000
    accept-count: 1000
    connection-timeout: 5000

spring:
  application:
    name: concert-service
  datasource:
    url: jdbc:mysql://localhost:3309/ticketing_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false&rewriteBatchedStatements=true
    username: developer
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 5000
      validation-timeout: 3000
      pool-name: ConcertHikariPool
      leak-detection-threshold: 60000

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 500

  kafka:
    bootstrap-servers: localhost:9092,kafka:9092
    consumer:
      group-id: concert-service-group

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

gateway:
  ip: 172.30.1.0/24