# eureka-server/src/main/resources/application.yml
server:
  port: 8761

spring:
  applicatin:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
