server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:hyeseong-dev/ticketing-config.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEArvD3YiQkdVVqmkqNyRP2Allg58vslQlfq8XmQzEH2qyJT8q0
            9K7rIap9HdvKtsTFG7BG3DPPlmkZmvyZbQXSdBsRKXVAN+oe4h89EEAK2C8fY2MU
            tEDC0aIOWpsbVefE9IP0cTEixjOxqpIv9XE5RNpl6a2uHjQ5kfXNi+hfxjwreGIF
            VGAg9NjraPS0Q7dKl4uxx7zem7Ddm4MI5LcAIcbaogNUC77EEW5aLJ30hUs5YWQW
            1IoS8u3IPMnmGxq9O2vF5RBAJF9bn2g6LdjvVcsCL46LmzIwve7OYriEwZvb44ht
            eQ+BDTiionpBQNNKfmgZ0q2Ui0vP906QhEbv6buKYYs8358NjlSfZAGJlo2lKnbX
            u0TjuiJMhWZGT5QO3IHbX1xWXb5lhEHx9EiH/gPO3mIMokKO3rWxqWAp1Cn/2Rnt
            HXL0r0xw0rzHpL/cqPtgy96qmG6UViIkQXve4GwSEAO4WWz2PQAc0xBMQnjDMeq2
            8YG8h676YlfbEMAW20JRXpcSpor+UIipkr82sk9mulU9Mb7FbCJbJuEG08iZREEK
            1ltwiK39ICGH/I98h46i0r6qFeC3mlS6tOof2RA0XzNObf2xLl85A+PwukqpU+cw
            RIojjuM8pkqPfNbPjV/FeWg6ISFt+lwoEOcyyPvwXjYoksEkxb8dRjYlYTcCAwEA
            AQKCAgAx/zgUWlP5HKJM2kXPU98ZKMYjOQqyRW2MQBDg3yBphKnxnfM9gsg8ZOdB
            I1G6Dl5u3WBDCqOnTv48ZzjKCcHt4NZ0zMe/sy+EXH0tKcBvrHgCBY0jPubu1qvX
            hUC4unZ1k0jHGM3ha2C5aPI/6U3+uZQqxrJee3qAlolaFN1aYFPkIc94H8kLcPtG
            kbj7KWUuDoSOmxHb2R5clYRzKUHmZViSuPTKLokGmk03NyVs+uS5Ssujjpp/xylV
            Bja3RFsUomZ6YrySKJac5kLKW5d7I3vKb6jCgAOiJJ/jYuy+EHc1fgYbdSzixG7m
            lJ4Vks1Vdxb6ORWdAdu7yD5RL5zc7N/IIloJnF+5qvmiZ7uOlwUqr4q5Qsf3udAm
            VHLeciNb2P7F55lhnBkx6L+zVvZDuMdIiMrsBTfV3HdkC8zGW8nufyBHgmsDbrRS
            1nKLmesfLnVeYjJglcl3qv8Vsqm3GhOLTdBaSJq5+kNMP7JoF9hVXLy1Zgtx7WAZ
            qBcDDaYEZ74uWlAug3Sao9Nt8v5zIH1TvdDdP9VqnOzSvofOask5uiWDqvY2nYEu
            LhxN5omHuiE1Xg/c6q/3Tu5uwTn10x/DQtoHS7bzHQCodWoTZo702e0B+jEVfk95
            takRFOpjIESr4N6+FnUVFxZzBlS3GxkczsvwK1yQOGs2lgou4QKCAQEA3XMWywfl
            uUU8TVYjBFb5SnqnB0vfwGAg+EuXLGSJKtrhzSRRdAgrj6Y4ziBC6yEVr9qNLD1h
            wgRC4+AflUnrwNT7q+gl5AUqVxH1KMS/vpFVTiB8TE67T1waprxIo7pI99azhsH+
            xTgtxxA1TT+JZ1WIE886wZF6PU2dZN5fckcdIog64aDaYXrYSzfqy7UnV8sUT2lL
            XAv5kbjveAVSgb7PbyBh0ub64S/xM9JaUHrcjH9aOav5HHCnHC2agSK/iEnQnCKK
            55JCHFyQTh1mKMu9gR/XTQ0M3JC78d8xamfbWZBvK+9R/isaNIRXf4/1/AvIKach
            2/6vqaPjIw6A3wKCAQEAyjxKecKahGvevmQbKjhntB77Uisa44s+0nncwBWebqVC
            WSitUyvDgchQwZ9Iy9gYiLnh880N0dAU4sblyeEbxGIUVT4XGCeBU6C5SwF48LEH
            R2Px+tNygo6s+Vv9TbHrybPBuLIfYMrKPbTOfPOhqkjTWRPOAM5NbQ4EHqIdBoFJ
            wkMHU9IsHalwFotM1claNvBb7VOZLgMHimGnW/WL2P7cUm6SYKfuBqWa+CwpaQeK
            pbsOB3MfqCLy6G70vvo3EO3U/8ubt1EZo6kRSN4reanSToequlN/mfiXldsJp1kt
            9LcMEsK34smQvfAuVjoGv7SV8NTiUi5t7YRVvrFyqQKCAQAE1rbwyMNkQPcIWZF6
            TswzrGpp5maFNZSC2GP9PFUi8pVsfhapimQpR2CGYH4V1Ss8JHJhPRYdvyoXAJaw
            FGVqWT0GjJQHX3WFYYcR1Pq7l0Fd66fLowzEtyZ97i9IJJHjmHVjxGlktc2KQ/hm
            L7U45M2MYULPZ/Zb0I5X3eQIAzXHw2JF+9XJu31uZ1JiERtC99UBxzM2V6ykWn4h
            CTy8SQcPTo3UpedldD64+yeuCoE3MLEwAWn4DR4Zp4VwvOmieLpuLvMKDFAVfpBI
            pKvOyGTjpWZ28IoPZ7ozlsTlpk9MrbNAKoKIIzj3XMzspKCjWT6OanB69h2wfzw/
            T9nRAoIBAQCI8uMMKTgxzEp+a5Ppt2CinQhb0EzZIgZcyaEvgnRTQR34+o7E77Hp
            RRlKxO6q+59Bl37ndkiReHNsTnx1hTckebaDMxS4iqgNVZ2kqU6Yz4i6U3gd/upg
            dvWztxOFdaLSaCQbSqPtC+aAetwJyYIEqmRUwhCSgyHzY7ZueCFnsk2ce3+Ox5iQ
            TZlV6ucRLtUktwfJYv8sJWkJ0K9gmpslSxEv0SjWw2FwptyWinFQaob9S/poGRGq
            7l/H/rtGSHLZx/Shc+Py87yFE4xc5/ZQ4StFeqGmo7yZK7qbBEU5Si7QtNQ8MBgO
            P6kAtpDqW0kOsN+IwuCv/jj6ys6137xhAoIBAGAHoQW4KQ5ZMRZrimDrbDVgGWX8
            zXU9vp9oZvy9eY3xumdAs6lOdNq10zXEuHkbVqALD4+kOWlAo++1nlShJxOPoxpp
            bZFeKJNqGDX1g7IzzLCzFv+JZBi3+V91ypsMaTA9qD1YrusmVusKg8NavlnJ5E1b
            jSE82UKzUSWsHmhTjQLBIk3vThSUw9XqoC9FwSZpRD6VXlzhogVE3RlL3EJDrnwv
            0f+bzPXg833b5ZVQc02yu4pOhMHe168aCfiWuQG7jaOhMh8Sh7jVgiyujMPMpe5s
            30wErrRY2sTJQytYqC9Gp4EfxINC95tyzoMGbkvyJDrkW9naYqWc9u6ylXI=
            -----END RSA PRIVATE KEY-----
          



