name: EC2 파일 전송 및 명령어 실행

on:
  push:
    branches: [ ec2_branch ]

env:
  EC2_USER: ubuntu
  EC2_HOST: ${{ secrets.EC2_HOST }}
  REMOTE_TARGET: /home/ubuntu

jobs:
  deploy-to-ec2:
    name: 파일 전송 및 명령어 실행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy prod-deploy-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          source: "prod-deploy-compose.yml"
          target: ${{ env.REMOTE_TARGET }}

      - name: Verify file on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          script: |
            ls -al /home/ubuntu/prod-deploy-compose.yml

      - name: SSH to EC2 and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key: ${{ secrets.SSH_PEM_KEY }}
          script: |
            if [ -f /home/ubuntu/prod-deploy-compose.yml ]; then rm /home/ubuntu/prod-deploy-compose.yml; fi
            echo "hello world!"
