CREATE USER 'developer'@'%' IDENTIFIED BY '12345';
GRANT USAGE ON *.* TO 'developer'@'%';
GRANT CREATE, ALTER, DROP, SELECT, INSERT, UPDATE, DELETE ON ticketing.* TO 'developer'@'%';
FLUSH PRIVILEGES;